from pydantic import BaseModel
import datetime


class TweetText(BaseModel):
    class Config:
        schema_extra = {
            "example": {
                "_api": "",
                "_json": {
                    "created_at": "Mon May 24 23:00:07 +0000 2021",
                    "id": 1396964253781819395,
                    "id_str": "1396964253781819395",
                    "text": "@username hello!!!",
                    "truncated": False,
                    "entities": {
                        "hashtags": [],
                        "symbols": [],
                        "user_mentions": [
                            {
                                "screen_name": "xxxxxxxx",
                                "name": "xxxxxxxx",
                                "id": 113212312312,
                                "id_str": "113212312312",
                                "indices": [0, 10],
                            },
                        ],
                        "urls": [],
                    },
                    "source": '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                    "in_reply_to_status_id": 1396917534889238531,
                    "in_reply_to_status_id_str": "1396917534889238531",
                    "in_reply_to_user_id": 42054308,
                    "in_reply_to_user_id_str": "42054308",
                    "in_reply_to_screen_name": "IamUpshod",
                    "user": {
                        "id": 44196397,
                        "id_str": "44196397",
                        "name": "Elon Musk",
                        "screen_name": "elonmusk",
                        "location": "",
                        "description": "",
                        "url": None,
                        "entities": {
                            "description": {
                                "urls": [],
                            },
                        },
                        "protected": False,
                        "followers_count": 55895758,
                        "friends_count": 106,
                        "listed_count": 73172,
                        "created_at": "Tue Jun 02 20:12:29 +0000 2009",
                        "favourites_count": 8823,
                        "utc_offset": None,
                        "time_zone": None,
                        "geo_enabled": False,
                        "verified": True,
                        "statuses_count": 14350,
                        "lang": None,
                        "contributors_enabled": False,
                        "is_translator": False,
                        "is_translation_enabled": False,
                        "profile_background_color": "C0DEED",
                        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_tile": False,
                        "profile_image_url": "http://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_image_url_https": "https://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1576183471",
                        "profile_link_color": "0084B4",
                        "profile_sidebar_border_color": "C0DEED",
                        "profile_sidebar_fill_color": "DDEEF6",
                        "profile_text_color": "333333",
                        "profile_use_background_image": True,
                        "has_extended_profile": True,
                        "default_profile": False,
                        "default_profile_image": False,
                        "following": None,
                        "follow_request_sent": None,
                        "notifications": None,
                        "translator_type": "none",
                        "withheld_in_countries": [],
                    },
                    "geo": None,
                    "coordinates": None,
                    "place": None,
                    "contributors": None,
                    "is_quote_status": False,
                    "retweet_count": 1828,
                    "favorite_count": 12580,
                    "favorited": False,
                    "retweeted": False,
                    "lang": "en",
                },
                "created_at": datetime.datetime(2021, 5, 24, 23, 0, 7),
                "id": 1396964253781819395,
                "id_str": "1396964253781819395",
                "text": "@IamUpshod They told me they would appreciate help",
                "truncated": False,
                "entities": {
                    "hashtags": [],
                    "symbols": [],
                    "user_mentions": [
                        {
                            "screen_name": "IamUpshod",
                            "name": "Upshod",
                            "id": 42054308,
                            "id_str": "42054308",
                            "indices": [0, 10],
                        },
                    ],
                    "urls": [],
                },
                "source": "Twitter for iPhone",
                "source_url": "http://twitter.com/download/iphone",
                "in_reply_to_status_id": 1396917534889238531,
                "in_reply_to_status_id_str": "1396917534889238531",
                "in_reply_to_user_id": 42054308,
                "in_reply_to_user_id_str": "42054308",
                "in_reply_to_screen_name": "IamUpshod",
                "author": dict(
                    _api="",
                    _json={
                        "id": 44196397,
                        "id_str": "44196397",
                        "name": "Elon Musk",
                        "screen_name": "elonmusk",
                        "location": "",
                        "description": "",
                        "url": None,
                        "entities": {"description": {"urls": []}},
                        "protected": False,
                        "followers_count": 55895758,
                        "friends_count": 106,
                        "listed_count": 73172,
                        "created_at": "Tue Jun 02 20:12:29 +0000 2009",
                        "favourites_count": 8823,
                        "utc_offset": None,
                        "time_zone": None,
                        "geo_enabled": False,
                        "verified": True,
                        "statuses_count": 14350,
                        "lang": None,
                        "contributors_enabled": False,
                        "is_translator": False,
                        "is_translation_enabled": False,
                        "profile_background_color": "C0DEED",
                        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_tile": False,
                        "profile_image_url": "http://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_image_url_https": "https://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1576183471",
                        "profile_link_color": "0084B4",
                        "profile_sidebar_border_color": "C0DEED",
                        "profile_sidebar_fill_color": "DDEEF6",
                        "profile_text_color": "333333",
                        "profile_use_background_image": True,
                        "has_extended_profile": True,
                        "default_profile": False,
                        "default_profile_image": False,
                        "following": None,
                        "follow_request_sent": None,
                        "notifications": None,
                        "translator_type": "none",
                        "withheld_in_countries": [],
                    },
                    id=44196397,
                    id_str="44196397",
                    name="Elon Musk",
                    screen_name="elonmusk",
                    location="",
                    description="",
                    url=None,
                    entities={"description": {"urls": []}},
                    protected=False,
                    followers_count=55895758,
                    friends_count=106,
                    listed_count=73172,
                    created_at=datetime.datetime(2009, 6, 2, 20, 12, 29),
                    favourites_count=8823,
                    utc_offset=None,
                    time_zone=None,
                    geo_enabled=False,
                    verified=True,
                    statuses_count=14350,
                    lang=None,
                    contributors_enabled=False,
                    is_translator=False,
                    is_translation_enabled=False,
                    profile_background_color="C0DEED",
                    profile_background_image_url="http://abs.twimg.com/images/themes/theme1/bg.png",
                    profile_background_image_url_https="https://abs.twimg.com/images/themes/theme1/bg.png",
                    profile_background_tile=False,
                    profile_image_url="http://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                    profile_image_url_https="https://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                    profile_banner_url="https://pbs.twimg.com/profile_banners/44196397/1576183471",
                    profile_link_color="0084B4",
                    profile_sidebar_border_color="C0DEED",
                    profile_sidebar_fill_color="DDEEF6",
                    profile_text_color="333333",
                    profile_use_background_image=True,
                    has_extended_profile=True,
                    default_profile=False,
                    default_profile_image=False,
                    following=False,
                    follow_request_sent=None,
                    notifications=None,
                    translator_type="none",
                    withheld_in_countries=[],
                ),
                "user": dict(
                    _api="",
                    _json={
                        "id": 44196397,
                        "id_str": "44196397",
                        "name": "Elon Musk",
                        "screen_name": "elonmusk",
                        "location": "",
                        "description": "",
                        "url": None,
                        "entities": {"description": {"urls": []}},
                        "protected": False,
                        "followers_count": 55895758,
                        "friends_count": 106,
                        "listed_count": 73172,
                        "created_at": "Tue Jun 02 20:12:29 +0000 2009",
                        "favourites_count": 8823,
                        "utc_offset": None,
                        "time_zone": None,
                        "geo_enabled": False,
                        "verified": True,
                        "statuses_count": 14350,
                        "lang": None,
                        "contributors_enabled": False,
                        "is_translator": False,
                        "is_translation_enabled": False,
                        "profile_background_color": "C0DEED",
                        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                        "profile_background_tile": False,
                        "profile_image_url": "http://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_image_url_https": "https://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                        "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1576183471",
                        "profile_link_color": "0084B4",
                        "profile_sidebar_border_color": "C0DEED",
                        "profile_sidebar_fill_color": "DDEEF6",
                        "profile_text_color": "333333",
                        "profile_use_background_image": True,
                        "has_extended_profile": True,
                        "default_profile": False,
                        "default_profile_image": False,
                        "following": None,
                        "follow_request_sent": None,
                        "notifications": None,
                        "translator_type": "none",
                        "withheld_in_countries": [],
                    },
                    id=44196397,
                    id_str="44196397",
                    name="Elon Musk",
                    screen_name="elonmusk",
                    location="",
                    description="",
                    url=None,
                    entities={"description": {"urls": []}},
                    protected=False,
                    followers_count=55895758,
                    friends_count=106,
                    listed_count=73172,
                    created_at=datetime.datetime(2009, 6, 2, 20, 12, 29),
                    favourites_count=8823,
                    utc_offset=None,
                    time_zone=None,
                    geo_enabled=False,
                    verified=True,
                    statuses_count=14350,
                    lang=None,
                    contributors_enabled=False,
                    is_translator=False,
                    is_translation_enabled=False,
                    profile_background_color="C0DEED",
                    profile_background_image_url="http://abs.twimg.com/images/themes/theme1/bg.png",
                    profile_background_image_url_https="https://abs.twimg.com/images/themes/theme1/bg.png",
                    profile_background_tile=False,
                    profile_image_url="http://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                    profile_image_url_https="https://pbs.twimg.com/profile_images/1383184766959120385/MM9DHPWC_normal.jpg",
                    profile_banner_url="https://pbs.twimg.com/profile_banners/44196397/1576183471",
                    profile_link_color="0084B4",
                    profile_sidebar_border_color="C0DEED",
                    profile_sidebar_fill_color="DDEEF6",
                    profile_text_color="333333",
                    profile_use_background_image=True,
                    has_extended_profile=True,
                    default_profile=False,
                    default_profile_image=False,
                    following=False,
                    follow_request_sent=None,
                    notifications=None,
                    translator_type="none",
                    withheld_in_countries=[],
                ),
                "geo": None,
                "coordinates": None,
                "place": None,
                "contributors": None,
                "is_quote_status": False,
                "retweet_count": 1828,
                "favorite_count": 12580,
                "favorited": False,
                "retweeted": False,
                "lang": "en",
            }
        }

    created_at: datetime.datetime
    screen_name: str
    name: str
    tweet_id: str
    text: str

    @staticmethod
    def parse(status) -> "TweetText":
        return TweetText(
            created_at=status.created_at,
            tweet_id=status.id_str,
            text=status.text,
            name=status.user.name,
            screen_name=status.user.screen_name,
        )

    def summalize(self):
        return f"https://twitter.com/{self.screen_name}/status/{self.tweet_id}"
